### ISSUE TITLE
На почту не приходит подтверждение о регистрации нового пользователя в web-version ( требуется подтверждение почты) 

### ISSUE THREAD

**Issue by Samohin13** [oleg-sung/ImpulseV2#14]
## Описание

**Не возможно подтвердить успешную регистрацию по указанной почте  , так как указанную  почту не приходит соответствующее письмо.**

## Шаги воспроизведение

1. В поле Email ввести корректную почту user_name234@mail.ru
2. Ввести имя в поле "Имя" пример: "Иван"
3. Ввести фамилию в поле "Фамилия" (например, "Иванов")
4. Выбрать дату рождения в поле "Дата рождения"(например, "01.01.1990")
5. Ввести название клуба в поле "Название клуба" (например, "Новый).
6. Ввести пароль, соответствующий требованиям (например, "user1234"),
7. Ввести тот же пароль в поле "Подтверждение пароля"
8. Отметить чекбокс "Согласие на обработку персональных данных"
9. Нажать кнопку "Регистрация".
10. Пользователя перенаправляет на стартовую страницу с текстом (***Нужно подтверждение почты
На почтовый адрес user_name234@mail.ru отправленно письмо для поддтверждения***)

- ***Скриншоты***
![image](https://github.com/user-attachments/assets/a5a19507-5a21-4e3e-943f-1492b08105b3)

- ***Почта пользователя User_name234@mail.ru***
![Снимок экрана 2024-11-18 150217](https://github.com/user-attachments/assets/2d8a3bac-51cf-4e81-8549-c5bf7ae197c7)

## Фактический результат 
- На почту не приходит ссылка на подтверждение о регистрации 
## Ожидаемый результат 
- На указанную почту должно прийти подтверждении в виде ссылке , при взаимодействие с которой , регистрация подтверждается и перенаправляет пользователя вновь в личный кабинете 

## Окружение 
- Windows 11 x64
- Google ChromeВерсия 130.0.6723.117 (Официальная сборка), (64 бит)

**Comment by oleg-sung** [comment]
@Samohin13 Привет!
Мы отказались от этой функции, из-за сложности реализации на мобильных приложения. Поэтому, в web версии приложения подтверждения почты не будет, достаточно логина и пароля. По этой проблеме я изменю редирект на экран входа.

**Comment by oleg-sung** [comment]
@Samohin13 Привет!
Проверь на этой ветке https://github.com/oleg-sung/ImpulseV2/pull/32, если все ок - закрывай тикет, я сделаю мёрдж в develop

**Comment by Samohin13** [comment]
@oleg-sung 
**После регистрации формы , страница перенаправляет в форму "Вход". Избегая редирект с кнопкой "Вход" и сообщении подтверждении регистрации по почте.**
