### ISSUE TITLE
После успешной регистрации, вход в личный кабинет невозможен с валидными (корректными) данными.

### ISSUE THREAD

**Issue by Samohin13** [oleg-sung/ImpulseV2#15]
## Описание 
***Вход в личный кабинет невозможен из-за долгой загрузки.*** 

## Шаги воспроизведение 
 - ***Предусловие открыть [страницу](http://127.0.0.1:8000/pages/login/)***
1. В поле Email ввести  user_name234@mail.ru
2. В поле пароль ввести user1234
3. Поставить галку в чек-боксе "Запомнить меня"
4. Нажать кнопку "Войти"

- ***Скриншоты:***
![Снимок экрана 2024-11-18 145948](https://github.com/user-attachments/assets/219d07fd-03dc-4adb-b524-96dfe4b8ce2d)

## Фактический результат 
Загрузка продолжительная и безрезультатная. Вход в личный кабинет не происходит. 

## Ожидаемый результат 
После нажатия на кнопку вход, пользователя перенаправляет в личный кабинет. 

## Окружение 
- Windows 11 x64
- Google ChromeВерсия 130.0.6723.117 (Официальная сборка), (64 бит)

**Comment by oleg-sung** [comment]
@Samohin13 Привет!
Этот баг мы закрываем?

**Comment by Samohin13** [comment]
Отработало корректно
