### ISSUE TITLE
"Ошибка сервиса. Нет корректного сообщения об ошибке " при валидации поля "Фамилия"

### ISSUE THREAD

**Issue by Samohin13** [oleg-sung/ImpulseV2#19]
##  Описание:
Нужно корректное сообщение об ошибке валидации поля "Фамилия" в форме регистрация.

с дефисом
с 1 буквой
граничные (57, 99, 100,101) символы
со спец.символами
с пробелами
с цифрами

### Предусловие:
- **Все остальные поля заполнены корректно:**

## Шаги:
1. Открыть [страницу](http://127.0.0.1:8000/pages/register/
2.В поле "Фамилия "ввести не валидные варианты имению.
2.Заполнить остальные поля.
4.Нажать кнопку "Регистрация"

## Фактический результат:
**Скрины:**
Под полем регистрация вылезает сообщение "Ошибка сервиса"
![Снимок экрана 2024-11-22 135813](https://github.com/user-attachments/assets/08844f23-4dca-4e8e-b4d6-e323be50465a)
![Снимок экрана 2024-11-22 135857](https://github.com/user-attachments/assets/16eabe58-6ce5-4f3a-a78b-9ba166f4b1c3)
![Снимок экрана 2024-11-22 135915](https://github.com/user-attachments/assets/4b56847e-167a-47ac-96c1-136b032169dc)
![Снимок экрана 2024-11-22 135957](https://github.com/user-attachments/assets/e1cdde2d-58ae-4524-b9eb-2f6e0e87095e)
![Снимок экрана 2024-11-22 140031](https://github.com/user-attachments/assets/cfc4b51b-a178-4659-aca0-9c07295e071b)
![Снимок экрана 2024-11-22 140056](https://github.com/user-attachments/assets/723789b6-0bfb-408d-bd06-1a07d4fa4e9f)
![Снимок экрана 2024-11-22 140153](https://github.com/user-attachments/assets/bb149531-3460-4be1-8ad4-307bb9209f35)

## Ожидаемый результат:
Пример сообщения которое должно всплывать под полем фамилия - "Значение может состоять из кириллических букв и дефиса"

## Окружение (OC):

- Windows 11 x64
- Google ChromeВерсия 130.0.6723.117 (Официальная сборка), (64 бит)
- Branch: develop

**Comment by oleg-sung** [comment]
@Samohin13 Привет 
Смотри эту ветку https://github.com/oleg-sung/ImpulseV2/pull/50

**Comment by Samohin13** [comment]
### Некорректное сообщение об ошибке при валидации поля "Фамилия"
- ввод 1 буквы
- ввод 21 буквы
- ввод спец символов
- ввод цифр


### Некорректная валидация граничного тестирования.
Поле имя должно принимать от 2 до 20 символов включительно.
- пропускает 21 символ 

![Снимок экрана 2024-12-03 162207](https://github.com/user-attachments/assets/79bc455e-25ca-433f-81e7-5b67159981c2)
![Снимок экрана 2024-12-03 162227](https://github.com/user-attachments/assets/a6f41214-6518-409c-acbc-897cd4967844)


### Некорректная валидация при двойной фамилии с (- )
- не пропускает (-)
![Снимок экрана 2024-12-03 161512](https://github.com/user-attachments/assets/02a24ca8-050d-4e99-a77c-90c869dc4ded)


### НОВОЕ Сообщение об ошибке.
Для поля "Фамилия"

Некорректное имя. Допустимы 2-20 букв и дефис.
Для поля "Фамилия"
Некорректная фамилия . Допустимы 2-20 букв и дефис.
Для поля "Отчество"
Некорректное отчество . Допустимы 2-20 букв и дефис.
Для поля "Название клуба"
Некорректное название . Допустимы 2-20 букв(А-я,A-z,0-9)и дефис.

**Comment by Samohin13** [comment]
Все супер. Отрабатывает отлично. Сообщения об ошибках обновлены и успешно применяются. @oleg-sung
