### ISSUE TITLE
При регистрации и редактировании профиля админа поле "дата рождения" неверно валидирует значение возраста

### ISSUE THREAD

**Issue by ischeglov** [oleg-sung/ImpulseV2#5]
# Описание
При регистрации и переходе на редактирование профиля админа поле "дата рождения" неверно валидирует значение возраста

# Фактический результат
<img width="574" alt="Снимок экрана 2024-08-25 в 17 17 56" src="https://github.com/user-attachments/assets/c5f9543a-d8ff-4669-8920-c9fe73c98a29">

<img width="835" alt="Снимок экрана 2024-08-25 в 16 56 53" src="https://github.com/user-attachments/assets/4a834887-7572-40d8-a5ce-9478de97954c">

# Информация с базы данных
<img width="791" alt="Снимок экрана 2024-08-25 в 16 59 40" src="https://github.com/user-attachments/assets/4a352b66-6e65-4577-bc08-0088b1350f77">

# Ожидаемый результат
Валидация поля "дата рождения" имеет ограничение (минимальный возраст 5 лет)

# Окружение
* **Device:** MacBook Air, macOS Sonoma 14.6.1
* **Browser:** Google Chrome, ver. 127.0.6533.120 (arm64)
* **Branch:** master, commit 099df1afc370da557145dd930dc5e3d78bf194b2

**Comment by oleg-sung** [comment]
Привет @ischeglov 

Добавил валидацию даты рождения при регистрации и обнавлении профиля. Во время регистрации так же вывел сообщения об ошибке в корректной форме. 

![Screenshot 2024-08-26 221657](https://github.com/user-attachments/assets/71ee33a3-9632-465f-a711-695eb63a16bf)

**Comment by ischeglov** [comment]
Привет! @oleg-sung Протестировано ✅
