### ISSUE TITLE
Опечатка в тексте "редактировать профиль" во вкладке администратор

### ISSUE THREAD

**Issue by ischeglov** [oleg-sung/ImpulseV2#7]
# Описание
При переходе на редактирование профиля во вкладке администратор допущена опечатка в тексте "РедакСтировать профиль"

# Фактический результат
<img width="1384" alt="Снимок экрана 2024-08-25 в 18 42 09" src="https://github.com/user-attachments/assets/3c8db7ef-9d08-4502-947b-04e85ab7306f">

# Ожидаемый результат
<img width="1385" alt="Снимок экрана 2024-08-25 в 18 45 09" src="https://github.com/user-attachments/assets/5252b0b0-51fd-4cc1-a8a8-befe0f0f5ed1">

# Окружение
* **Device:** MacBook Air, macOS Sonoma 14.6.1
* **Browser:** Google Chrome, ver. 127.0.6533.120 (arm64)
* **Branch:** master, commit 099df1afc370da557145dd930dc5e3d78bf194b2

**Comment by oleg-sung** [comment]
Привет! 
Изменения в ветке develop.

**Comment by ischeglov** [comment]
Протестировано ✅
